### ISSUE TITLE
Extra parameters, derived quants for model with rawSPR and no recdevs

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/stock-synthesis#135] opened 2021-02-18 01:38 UTC
The attached files from Jason Cope have two elements of the output that seem strange.

First, the only SPRratio values reported are SPRratio_2019 and SPRratio_2020, as compared to Bratio which goes from Bratio_1992 to Bratio_2020. The starter file has 
`4 # SPR_report_basis:  0=skip; 1=(1-SPR)/(1-SPR_tgt); 2=(1-SPR)/(1-SPR_MSY); 3=(1-SPR)/(1-SPR_Btarget); 4=rawSPR`
so perhaps there's no point in including SPRratio in the derived quantities. That would be reasonable, but then I think it would be better to leave SPRratio values out of the derived quantities entirely instead of reporting it for endyr and endyr + 1.

Second, although the control file has 
`0 #do_recdev:  0=none; 1=devvector (R=F(SSB)+dev); 2=deviations (R=F(SSB)+dev); 3=deviations (R=R0*dev; dev2=R-f(SSB)); 4=like 3 with sum(dev2) adding penalty`
there is a `ForeRecr_2020` parameter included in the table of parameters. When a 3-year retrospective was run, there appeared `Late_RecrDev_2017` through `Late_RecrDev_2019`.  I think for models with do_recdev = 0 it would be best to completely exclude all recdevs from the output.

I also see there is a `Impl_err_2020` parameter listed in spite of this setting in the forecast file:
`0 # stddev of log(realized catch/target catch) in forecast (set value>0.0 to cause active impl_error)`

These things came up because they caused problems for r4ss. None of this impacts model results, and work arounds in r4ss were easy to add. But I think the additional output could be confusing and isn't adding anything useful.

Lastly, I noticed a missing comment character in the forecast.ss_new file and just pushed a fix for that in commit 14ab0adb8befe1d54b97f1f49d4e4d0c4c6d2f32.

Model files: [Scenario 1.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/5999592/Scenario.1.zip)

**Comment by Rick-Methot-NOAA** [comment] 2021-03-16 00:04
Just now picking this up.  Let me know if you have any new info to share.
This is a strange example.  No fleets have retained catch, so totcat(y) is and this causes std_err reporting indexes to be miscounted.  What is the intent of having all fleets be bycatch only fleets?

**Comment by k-doering-NOAA** [comment] 2021-03-16 00:10
I think this is a scenario from Jason's datalimited tool: https://github.com/shcaba/SS-DL-tool . @shcaba

**Comment by Rick-Methot-NOAA** [comment] 2021-03-16 16:22
Issue 1 was due to the user file not having any fleet with retained catch because SS is looking to do the SPR se in years with totcat(y)>0.  Problem resolved but setting fleets as type 1, not 2, and setting catch lambda = 0 so the read catch amount does not influence the logL and F parameters.

Issues 2 and 3 will be addressed next.

**Comment by Rick-Methot-NOAA** [comment] 2021-03-16 21:38
Issue 3 is now resolved.  Biggest challenge was in resolving all references to the number of active parameters.  Now if implementation error = 0, then Do_Impl_Error is set to 0 and nothing regarding implementation error is reported.   Previously, some got reported as a routine part of Do_Forecast, even if it was zero.
A consequence of this is that the number of parameters is decreased except when implementation error is >0.  So, old ss.par files will not work, so expect to see lots of failed Jenkins runs

**Comment by iantaylor-NOAA** [comment] 2021-03-16 21:44
Thanks, @Rick-Methot-NOAA. I suspect that having fewer parameters that weren't requested is worth the cost of some failed ss.par file reads. In general it seems like a bad idea to carry .par files across different model versions. I don't know if anyone would see this if we put it in the user manual, but I would guess that best practice is always to re-run with estimation from starting values in the control file when changing versions except in cases where you're trying to track down the source of differences between versions.

**Comment by k-doering-NOAA** [comment] 2021-03-16 22:01
ok, thanks, Rick! I just check and I think this won't break code in the r4ss function to read par files (https://github.com/r4ss/r4ss/blob/development/R/SS_readpar_3.30.R), which is helpful.

You are right, though, it will break the no estimation runs on jenkins, but running with estimation should work fine as the ss_summary.sso is used to do the comparison.

**Comment by Rick-Methot-NOAA** [comment] 2021-03-17 01:06
Now, if do_recdev==0, the Fore_Recruitment vector has null length and the reporting does not show devs for the forecast years.  
In several places, I needed to add logic addressing do_recdev.  
This has only been tested with simple example, so needs a full test and perhaps an added manual test with retro_years.  As with the associated change for impl_error, this change will break reading of prior ss.par files.
Pushing now to the test branch.

**Comment by k-doering-NOAA** [comment] 2021-03-19 23:08
Jenkins ran the model test set with estimation and hessian on the branch reduce-extra-fcast-quantities ; The [three area double normal selectivity](https://github.com/nmfs-stock-synthesis/ss-test-models/tree/main/models/three_area_double_normal_selex) model did not run all the way through. I tested locally using this [github compiled exe](https://github.com/nmfs-stock-synthesis/stock-synthesis/runs/2126847397) with options `-stopph 0 -nohess` and was able to replicate the error: 

```
 finished SS_summary.sso
 finished SS_summary.sso
 writing big output now
array bound exceeded -- index too high in prevariable::operator()
```

Pretty sure that commit b3506bb is the cause

**Comment by Rick-Methot-NOAA** [comment] 2021-03-19 23:13
Back on my workbench

**Comment by Rick-Methot-NOAA** [comment] 2021-03-20 01:10
This is a very strange example.
Code tweaked so it now runs.  
User will now get this warning:
Implementation error incompatible with neg. phase for forecast rec_devs; SS will run without active impl error

**Comment by k-doering-NOAA** [comment] 2021-03-22 15:22
Thanks, I confirmed the model now runs (with -stopph 0 and -nohess) and that the new error shows up. Jenkins testing was just restarted on the reduce-extra-fcast-quantities branch.

Given that the example is "strange" do you think it should be modified for testing purposes?

**Comment by Rick-Methot-NOAA** [comment] 2021-03-22 15:42
I do not know the full history of this example, but I suspect it was assembled just to demonstrate model configuration, but not to actually run or to have realistic looking data.  I would replace this one with the super-example I was once working on.

**Comment by k-doering-NOAA** [comment] 2021-03-22 15:46
@Rick-Methot-NOAA , yep, I think this is a made up example for the configuration. I guess I'll leave it as-is for the time being?

**Comment by Rick-Methot-NOAA** [comment] 2021-03-22 15:48
OK for now.  But meaningless to run it with Hessian.

**Comment by iantaylor-NOAA** [comment] 2021-03-22 18:15
I think this model was a simplified version of the 2009 Yelloweye Rockfish assessment that Ian Stewart created long ago. The catch history looks very similar to YelloweyeRF_2017 which is in our set as well. 

Any strange settings may be the accidental result of many conversions starting with SS version 3.03 that was used in 2009 (I just looked it up out of curiosity). I'm not aware of anything special about this model which makes it worth keeping, as CanaryRf_2015 also has three areas areas and double-normal selectivity.

I would suggest just dropping it from the set.

**Comment by k-doering-NOAA** [comment] 2021-03-22 18:25
That makes sense to me. Note that the CanaryRF_2015 model isn't very stable so it is run, but its results are not compared to a reference file; but still, we have a yelloweye model with 2 areas and double normal selectivity as well as a 3 area model. It seems fine to drop this one to me. An additional advantage is this model takes an hour to run with hessian, so it will speed up Jenkins runs!

**Closed** 2021-03-22 21:53 UTC
Labels: Resolved, misc. output

**Comment by Rick-Methot-NOAA** [comment] 2021-04-01 20:06
one more tweak to correct the parameter label indexing in write_ssnew
